
@startjson
{
	"event": {
	   "eventID" : [
	       { "CodedValueType" : "(110100, DCM, Application Activity)"}
	       ],
	   "EventActionCode": "C",
	   "EventDateTime" : "date-time",
	   "EventOutcomeIndicator": "0",
	   "EventTypeCode" : [
	   	{ "code" : "(110120, DCM, Application Start)"}
		],
	   "traceID" : "asdf",
	   "parentID" : "lkjl",
	   "childID" : "huh"
	   },
	"ActiveParticipant" : {
	   "UserID" : "thisuser",
	   "AlternativeUserID" : "theotherID",
	   "Username" : "if known",
	   "UserIsRequestor" : "TRUE",
	   "RoleIDCode" : [
	   	{ "code" : "(110150, DCM, Application)"}
		]
	   },
	"ActiveParticipant" : {
	   "UserID" : "thatuser",
	   "AlternativeUserID" : "anotherID",
	   "Username" : "if known",
	   "UserIsRequestor" : "FALSE",
	   "RoleIDCode" : [
	   	{ "code" : "(110151, DCM, Application Launcher)"}
		]	   
	   }
}
@endjson


	   
