
@startjson
{
	"event": {
	   "eventID" : [
	       { "CodedValueType" : "(110105, DCM, DICOM Study Deleted)"}
	       ],
	   "EventActionCode": "D",
	   "EventDateTime" : "date-time",
	   "EventOutcomeIndicator": "0",
	   "EventTypeCode" : [
	   	{ "CodedValueType" : "not specialized (seems odd)"}
		],
	   "traceID" : "asdf",
	   "parentID" : "lkjl",
	   "childID" : "huh"
	   },
	"ActiveParticipant" : {
	   "UserID" : "UserID of the deleting process",
	   "AlternativeUserID" : "theotherID",
	   "Username" : "if known",
	   "UserIsRequestor" : "TRUE",
	   "RoleIDCode" : [
	   	{ "CodedValueType" : "(110153, DCM, Source Role ID)"}
		]
	   },
	"ParticipatingObject" : {
	   "ParticipantObjectTypeCode" : 2,
	   "ParticipantObjectTypeCodeRole" : 3,
	   "ParticipantObjectIDTypeCode" : [
	       { "CodedValueType" : "(110180, DCM, Study Instance UID)"}
	       ],
	   "ParticipantObjectID" : "study-instance-uid"
	   },
	"more participating objects" : [],
	"ParticipatingObject" : {
	    "ParticipantObjectTypeCode" : 1,
	    "ParticipantObjectTypeCodeRole" : 1,
	    "ParticipantObjectIDTypeCode" : [
	        { "CodedValueType" : "(2, RFC-3991, Patient Number)"}
	        ],
	    "ParticipantObjectID" : "the patient ID",
	    "ParticipantObjectName" : "the patient name"
	   }
}
@endjson


	   
