
@startjson
{
	"event": {
	   "eventID" : [
	       { "CodedValueType" : "(110108, DCM, Network Entry)"}
	       ],
	   "EventActionCode": "E",
	   "EventDateTime" : "date-time",
	   "EventOutcomeIndicator": "0",
	   "EventTypeCode" : [
	   	{ "CodedValueType" : "(110124, DCM, Detach)"}
		],
	   "traceID" : "asdf",
	   "parentID" : "lkjl",
	   "childID" : "huh"
	   },
	"ActiveParticipant" : {
	   "UserID" : "UserID of the system",
	   "AlternativeUserID" : "theotherID",
	   "Username" : "if known",
	   "UserIsRequestor" : "FALSE"
	   }
}
@endjson


	   
