
@startjson
{
	"event": {
	   "eventID" :
	       { "CodedValueType" : "(110113, DCM, Security Alert)"},
	   "EventActionCode": "E",
	   "EventDateTime" : "date-time",
	   "EventOutcomeIndicator": "0",
	   "EventTypeCode" : 
	   	{ "CodedValueType" : "(110126, DCM, Node Authentication)"}
	},
	"ActiveParticipant" : {
	   "UserID" : "UserID of the system that authenticated",
	   "AlternativeUserID" : "theotherID",
	   "Username" : "if known",
	   "UserIsRequestor" : "FALSE"
	   }
}
@endjson


	   
